# Generated by Django 4.0.2 on 2022-03-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_product_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
