# Generated by Django 4.0.2 on 2022-03-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categ',
            field=models.CharField(default='', max_length=255),
        ),
    ]
