# Generated by Django 4.0.2 on 2022-03-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_categ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categ',
        ),
    ]
