# Generated by Django 4.0.2 on 2022-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catImage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
