# Generated by Django 4.0.2 on 2022-03-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_catimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uimage', models.ImageField(default='', upload_to='')),
                ('uname', models.CharField(max_length=255)),
                ('uemail', models.EmailField(max_length=255)),
                ('umob', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='catImage',
            field=models.ImageField(default='', upload_to='category'),
        ),
    ]
