# Generated by Django 4.0.2 on 2022-03-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_users_alter_category_catimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='upass',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='uimage',
            field=models.ImageField(default='', upload_to='users'),
        ),
    ]
