# Generated by Django 4.0.2 on 2022-03-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_users_upass_alter_users_uimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.ImageField(default='', upload_to='users')),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.EmailField(max_length=255)),
                ('shipping', models.CharField(max_length=255)),
            ],
        ),
    ]
