# Generated by Django 4.0.2 on 2022-03-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_orders_name_alter_orders_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
