# Generated by Django 4.0.2 on 2022-04-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_orders_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
